### ISSUE TITLE
Raise warning if no username field in custom authentication_form

### ISSUE THREAD

**Issue by belugame** [PaesslerAG/django-act-as-auth#14]
see TODO at https://github.com/PaesslerAG/django-act-as-auth/blob/master/djactasauth/views.py#L29

**Comment by Eorhim** [comment]
@belugame Do you think, this became obsolete by converting to class based views and deriving from the standard `LoginView`?

**Comment by belugame** [comment]
yes, it is obsolete. thanks :)
